import Head from 'next/head'
import { Inter } from '@next/font/google'
import { imageOptimizer } from 'next/dist/server/image-optimizer'
import { isModuleBlock } from 'typescript'
const inter = Inter({ subsets: ['latin'] })
import Navbar from '../Components/Navbar'
import Styles from '../styles/Home.module.css'
import Image from 'next/image'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={Styles.header}>
        <Navbar />

      </header>

      <main className={Styles.container}>

        {/* home */}
        <section className={Styles.home} id="home">
          <div className={Styles['home__container']}>
            <div className={Styles["home__data"]}>
              <h1 className={Styles["home-title"]}>Tasty food</h1>
              <h2 className={Styles.subtitle}>Try the best food of <br /> the week. </h2>

              <Link href="#" className={Styles.button}>View Menu</Link>
            </div>
            <div className={Styles['home_img']}>
              <Image
                src='/images/home.png'
                width="420"
                height="420"
                alt="logo"
                className={Styles.homeImage}
              ></Image>
            </div>
          </div>
        </section>

        {/* about */}
        <section className={Styles.about} id="about">
          <div className={Styles["about__container"]}>
            <div className={Styles["about__data"]}>
              <span className={Styles['section-subtitle']}>About us</span>
              <h2 className={Styles.title}>We cook the best <br /> tasty food</h2>
              <p className={Styles["about-description"]}>We cook the best food in the entire city, <br /> with excellent customer service, the best meals and at the best price, visit us.</p>
              <Link href="#" className={Styles.button}>Explore history</Link>
            </div>

            <div className={Styles['about_img']}>
              <Image
                src='/images/about.jpg'
                width="420"
                height="420"
                alt="logo"
                className={Styles.aboutImage}
              ></Image>
            </div>
          </div>
        </section>

        {/* services */}
        <section className={Styles.services} id="services">
          <span className={Styles['section-subtitle']}>Offering</span>
          <h2 >Our amazing services</h2>

          <div className={Styles["services__container"]}>

            <div className={Styles["service-card"]}>
              <Image
                src='/images/about.jpg'
                width="120"
                height="120"
                alt="logo"
                className={Styles["service-image"]}
              ></Image>
              <h2 className={Styles["service-title"]}>
                Excellent food
              </h2>
              <p className={Styles["service-desciption"]}>
                We offer our clients excellent quality services for many years, with the best and delicious food in the city.
              </p>
            </div>

            <div className={Styles["service-card"]}>
              <Image
                src='/images/about.jpg'
                width="120"
                height="120"
                alt="logo"
                className={Styles["service-image"]}
              ></Image>
              <h2 className={Styles["service-title"]}>
                Fast food
              </h2>
              <p className={Styles["service-desciption"]}>
                We offer our clients excellent quality services for many years, with the best and delicious food in the city.
              </p>
            </div>

            <div className={Styles["service-card"]}>
              <Image
                src='/images/about.jpg'
                width="120"
                height="120"
                alt="logo"
                className={Styles["service-image"]}
              ></Image>
              <h2 className={Styles["service-title"]}>
                Delivery
              </h2>
              <p className={Styles["service-desciption"]}>
                We offer our clients excellent quality services for many years, with the best and delicious food in the city.
              </p>
            </div>
          </div>
        </section>



        {/* menu*/}


        <section className={Styles.menu} id="menu">
          <span className={Styles['section-subtitle']}>Special</span>
          <h2 className={Styles.title}>Menu of the week</h2>

          <div className={Styles["menu__container"]}>

            <div className={Styles["menu-card"]}>
              <Image
                src='/images/home.png'
                width="120"
                height="120"
                alt="logo"
                className={Styles["menu-image"]}
              ></Image>
              <h2 className={Styles["menu-title"]}>
                Barbecue salad
              </h2>
              <p className={Styles["menu-subtitle"]}>
                Delicious dish
              </p>
              <p className={Styles.price}>
                $55.00
              </p>
            </div>

            <div className={Styles["menu-card"]}>
              <Image
                src='/images/home.png'
                width="120"
                height="120"
                alt="logo"
                className={Styles["menu-image"]}
              ></Image>
              <h2 className={Styles["menu-title"]}>
                Barbecue salad
              </h2>
              <p className={Styles["menu-subtitle"]}>
                Delicious dish
              </p>
              <p className={Styles.price}>
                $55.00
              </p>
            </div>

            <div className={Styles["menu-card"]}>
              <Image
                src='/images/home.png'
                width="120"
                height="120"
                alt="logo"
                className={Styles["menu-image"]}
              ></Image>
              <h2 className={Styles["menu-title"]}>
                Barbecue salad
              </h2>
              <p className={Styles["menu-subtitle"]}>
                Delicious dish
              </p>
              <p className={Styles.price}>
                $55.00
              </p>
            </div>
          </div>

        </section>

      </main>

      {/* footer */}

      <footer className={Styles.footer}>
        <div className={Styles["footer__container"]}>

          <div className={Styles["footer__content"]}>
            <h3 className={Styles["footer__title"]}>Services</h3>
            <ul>
              <li>Delivery</li>
              <li>Pricing</li>
              <li>Fast food</li>
              <li>Reserve your spot</li>
            </ul>
          </div>

          <div className={Styles["footer__content"]}>
            <h3 className={Styles["footer__title"]}>Information</h3>
            <ul>
              <li>Event</li>
              <li>Contact us</li>
              <li>Privacy policy</li>
              <li>Terms of services</li>
            </ul>
          </div>

          <div className={Styles["footer__content"]}>
            <h3 className={Styles["footer__title"]}>Adress</h3>
            <ul>
              <li>Lima - Peru</li>
              <li>Jr Union #999</li>
              <li>999 - 888 - 777</li>
              <li>tastyfood@email.com</li>
            </ul>
          </div>
        </div>
        <p className={Styles["footer__copy"]}>&#169; 2023 MD KALAM. All right reserved</p>

      </footer>
    </>
  )
}

